#!/bin/sh
#
# Start the temperature monitor
#

case "$1" in
   start)
     echo -n "Starting temperature monitor..."
     start-stop-daemon -q -S -x /pi/bin/tempsense.bin
     echo "OK."
     ;;
   stop)
     echo -n "Stopping temperature monitor..."
     start-stop-daemon -q -K -x /pi/bin/tempsense.bin
     echo "OK"
     ;;
    *)
     echo $"Usage: $0 {start|stop}"
     exit 1
esac

exit $?


